run:
  concurrency: 4
  deadline: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - examples
    - api/images
    - test
  # skip-files:

linters:
  enable:
    - megacheck
    - govet
    - deadcode
    - gocyclo
    - golint
    - varcheck
    - structcheck
    - errcheck
    - dupl
    - ineffassign
    - interfacer
    - unconvert
  enable-all: false
