run:
  deadline: 20m
  timeout: 20m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - examples
    - api/images
    - test/functions
    - assets/
    - bundler/go/assets
linters:
  enable:
    - goimports
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - goconst
    - gocyclo
    - misspell
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - goconst
        - errcheck
        - dupl
        - gosec
