// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fx.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	fx.proto

It has these top-level messages:
	UpRequest
	DownRequest
	ListRequest
	UpResponse
	DownResponse
	ListResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpRequest struct {
	FunctionSource string `protobuf:"bytes,1,opt,name=FunctionSource,json=functionSource" json:"FunctionSource,omitempty"`
	LocalAddress   string `protobuf:"bytes,2,opt,name=LocalAddress,json=localAddress" json:"LocalAddress,omitempty"`
	RemoteAddress  string `protobuf:"bytes,3,opt,name=RemoteAddress,json=remoteAddress" json:"RemoteAddress,omitempty"`
}

func (m *UpRequest) Reset()                    { *m = UpRequest{} }
func (m *UpRequest) String() string            { return proto.CompactTextString(m) }
func (*UpRequest) ProtoMessage()               {}
func (*UpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpRequest) GetFunctionSource() string {
	if m != nil {
		return m.FunctionSource
	}
	return ""
}

func (m *UpRequest) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *UpRequest) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

type DownRequest struct {
}

func (m *DownRequest) Reset()                    { *m = DownRequest{} }
func (m *DownRequest) String() string            { return proto.CompactTextString(m) }
func (*DownRequest) ProtoMessage()               {}
func (*DownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UpResponse struct {
	FunctionID string `protobuf:"bytes,1,opt,name=FunctionID,json=functionID" json:"FunctionID,omitempty"`
	State      string `protobuf:"bytes,2,opt,name=State,json=state" json:"State,omitempty"`
	ServiceURL string `protobuf:"bytes,3,opt,name=ServiceURL,json=serviceURL" json:"ServiceURL,omitempty"`
}

func (m *UpResponse) Reset()                    { *m = UpResponse{} }
func (m *UpResponse) String() string            { return proto.CompactTextString(m) }
func (*UpResponse) ProtoMessage()               {}
func (*UpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpResponse) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *UpResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UpResponse) GetServiceURL() string {
	if m != nil {
		return m.ServiceURL
	}
	return ""
}

type DownResponse struct {
}

func (m *DownResponse) Reset()                    { *m = DownResponse{} }
func (m *DownResponse) String() string            { return proto.CompactTextString(m) }
func (*DownResponse) ProtoMessage()               {}
func (*DownResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListResponse struct {
	Instances []*UpResponse `protobuf:"bytes,1,rep,name=Instances,json=instances" json:"Instances,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListResponse) GetInstances() []*UpResponse {
	if m != nil {
		return m.Instances
	}
	return nil
}

func init() {
	proto.RegisterType((*UpRequest)(nil), "api.UpRequest")
	proto.RegisterType((*DownRequest)(nil), "api.DownRequest")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*UpResponse)(nil), "api.UpResponse")
	proto.RegisterType((*DownResponse)(nil), "api.DownResponse")
	proto.RegisterType((*ListResponse)(nil), "api.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FxService service

type FxServiceClient interface {
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error)
	Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type fxServiceClient struct {
	cc *grpc.ClientConn
}

func NewFxServiceClient(cc *grpc.ClientConn) FxServiceClient {
	return &fxServiceClient{cc}
}

func (c *fxServiceClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error) {
	out := new(UpResponse)
	err := grpc.Invoke(ctx, "/api.FxService/Up", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error) {
	out := new(DownResponse)
	err := grpc.Invoke(ctx, "/api.FxService/Down", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/api.FxService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FxService service

type FxServiceServer interface {
	Up(context.Context, *UpRequest) (*UpResponse, error)
	Down(context.Context, *DownRequest) (*DownResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterFxServiceServer(s *grpc.Server, srv FxServiceServer) {
	s.RegisterService(&_FxService_serviceDesc, srv)
}

func _FxService_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/Up",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).Up(ctx, req.(*UpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/Down",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).Down(ctx, req.(*DownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FxService",
	HandlerType: (*FxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _FxService_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _FxService_Down_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FxService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fx.proto",
}

func init() { proto.RegisterFile("fx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x86, 0x89, 0x5e, 0xc5, 0x1c, 0x93, 0xdc, 0xeb, 0xdc, 0xbb, 0x10, 0xb9, 0x14, 0x19, 0x4a,
	0x11, 0xa1, 0x86, 0xda, 0x4d, 0x11, 0x0a, 0x2d, 0x88, 0x20, 0xb8, 0x8a, 0xf8, 0x00, 0x63, 0x1c,
	0x65, 0x20, 0x9d, 0x99, 0x66, 0x26, 0xea, 0xa6, 0x9b, 0xbe, 0x42, 0x9f, 0xaa, 0xeb, 0xbe, 0x42,
	0x1f, 0xa4, 0x4c, 0x32, 0xb1, 0xb1, 0xcb, 0xf3, 0xe7, 0xff, 0xff, 0xf3, 0x9d, 0x21, 0xd0, 0xda,
	0x1e, 0x47, 0x32, 0x15, 0x5a, 0xa0, 0x3a, 0x91, 0xac, 0xf7, 0x7f, 0x27, 0xc4, 0x2e, 0xa1, 0x21,
	0x91, 0x2c, 0x24, 0x9c, 0x0b, 0x4d, 0x34, 0x13, 0x5c, 0x15, 0x16, 0xfc, 0x02, 0xee, 0x4a, 0x46,
	0xf4, 0x39, 0xa3, 0x4a, 0xa3, 0x2b, 0x08, 0x66, 0x19, 0x8f, 0xcd, 0xf7, 0xa5, 0xc8, 0xd2, 0x98,
	0x76, 0x9d, 0xbe, 0x33, 0x70, 0xa3, 0x60, 0x7b, 0xa6, 0x22, 0x0c, 0xde, 0x42, 0xc4, 0x24, 0x79,
	0xdc, 0x6c, 0x52, 0xaa, 0x54, 0xb7, 0x96, 0xbb, 0xbc, 0xa4, 0xa2, 0xa1, 0x4b, 0xf0, 0x23, 0xfa,
	0x24, 0x34, 0x2d, 0x4d, 0xf5, 0xdc, 0xe4, 0xa7, 0x55, 0x11, 0xfb, 0xd0, 0x9e, 0x8a, 0x03, 0xb7,
	0x00, 0x66, 0x5c, 0x30, 0xa5, 0xcb, 0x71, 0x0d, 0x60, 0xe0, 0x94, 0x14, 0x5c, 0x51, 0x74, 0x01,
	0x50, 0xd2, 0xcd, 0xa7, 0x96, 0x0c, 0xb6, 0x27, 0x05, 0xfd, 0x83, 0xc6, 0x52, 0x13, 0x4d, 0x2d,
	0x4e, 0x43, 0x99, 0xc1, 0xa4, 0x96, 0x34, 0xdd, 0xb3, 0x98, 0xae, 0xa2, 0x85, 0x85, 0x00, 0x75,
	0x52, 0x70, 0x00, 0x5e, 0x41, 0x50, 0x6c, 0xc1, 0xf7, 0xe0, 0x15, 0x08, 0x76, 0xeb, 0x35, 0xb8,
	0x73, 0xae, 0x34, 0xe1, 0x31, 0x55, 0x5d, 0xa7, 0x5f, 0x1f, 0xb4, 0xc7, 0xbf, 0x47, 0x44, 0xb2,
	0xd1, 0x37, 0x59, 0xe4, 0xb2, 0xd2, 0x31, 0x7e, 0x77, 0xc0, 0x9d, 0x1d, 0xed, 0x46, 0x74, 0x07,
	0xb5, 0x95, 0x44, 0xc1, 0xc9, 0x9f, 0x9f, 0xd5, 0xfb, 0x99, 0xc7, 0x9d, 0xd7, 0x8f, 0xcf, 0xb7,
	0x5a, 0x1b, 0x37, 0xc3, 0xfd, 0x4d, 0x98, 0xc9, 0x89, 0x33, 0x44, 0x0f, 0xf0, 0xcb, 0x60, 0xa1,
	0x3f, 0xb9, 0xb7, 0xf2, 0x46, 0xbd, 0x4e, 0x45, 0xb1, 0xf9, 0xbf, 0x79, 0xde, 0xc7, 0x2d, 0x93,
	0xdf, 0x88, 0x03, 0xb7, 0x0d, 0xe6, 0x10, 0xdb, 0x50, 0x79, 0x56, 0xdb, 0x50, 0xbd, 0xf2, 0xbc,
	0x21, 0x61, 0x4a, 0x4f, 0x9c, 0xe1, 0xba, 0x99, 0xff, 0x22, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0x4a, 0x45, 0xc7, 0x51, 0x02, 0x00, 0x00,
}
