// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fx.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	fx.proto

It has these top-level messages:
	FunctionMeta
	UpRequest
	DownRequest
	ListRequest
	UpMsgMeta
	UpResponse
	DownMsgMeta
	DownResponse
	ListItem
	ListResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FunctionMeta struct {
	Lang    string `protobuf:"bytes,1,opt,name=Lang,json=lang" json:"Lang,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=Path,json=path" json:"Path,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *FunctionMeta) Reset()                    { *m = FunctionMeta{} }
func (m *FunctionMeta) String() string            { return proto.CompactTextString(m) }
func (*FunctionMeta) ProtoMessage()               {}
func (*FunctionMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FunctionMeta) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *FunctionMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FunctionMeta) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpRequest struct {
	Functions []*FunctionMeta `protobuf:"bytes,1,rep,name=Functions,json=functions" json:"Functions,omitempty"`
}

func (m *UpRequest) Reset()                    { *m = UpRequest{} }
func (m *UpRequest) String() string            { return proto.CompactTextString(m) }
func (*UpRequest) ProtoMessage()               {}
func (*UpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpRequest) GetFunctions() []*FunctionMeta {
	if m != nil {
		return m.Functions
	}
	return nil
}

type DownRequest struct {
	ID []string `protobuf:"bytes,1,rep,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *DownRequest) Reset()                    { *m = DownRequest{} }
func (m *DownRequest) String() string            { return proto.CompactTextString(m) }
func (*DownRequest) ProtoMessage()               {}
func (*DownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DownRequest) GetID() []string {
	if m != nil {
		return m.ID
	}
	return nil
}

type ListRequest struct {
	ID []string `protobuf:"bytes,1,rep,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListRequest) GetID() []string {
	if m != nil {
		return m.ID
	}
	return nil
}

type UpMsgMeta struct {
	FunctionSource string `protobuf:"bytes,1,opt,name=FunctionSource,json=functionSource" json:"FunctionSource,omitempty"`
	LocalAddress   string `protobuf:"bytes,2,opt,name=LocalAddress,json=localAddress" json:"LocalAddress,omitempty"`
	RemoteAddress  string `protobuf:"bytes,3,opt,name=RemoteAddress,json=remoteAddress" json:"RemoteAddress,omitempty"`
}

func (m *UpMsgMeta) Reset()                    { *m = UpMsgMeta{} }
func (m *UpMsgMeta) String() string            { return proto.CompactTextString(m) }
func (*UpMsgMeta) ProtoMessage()               {}
func (*UpMsgMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpMsgMeta) GetFunctionSource() string {
	if m != nil {
		return m.FunctionSource
	}
	return ""
}

func (m *UpMsgMeta) GetLocalAddress() string {
	if m != nil {
		return m.LocalAddress
	}
	return ""
}

func (m *UpMsgMeta) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

type UpResponse struct {
	Instances []*UpMsgMeta `protobuf:"bytes,1,rep,name=Instances,json=instances" json:"Instances,omitempty"`
}

func (m *UpResponse) Reset()                    { *m = UpResponse{} }
func (m *UpResponse) String() string            { return proto.CompactTextString(m) }
func (*UpResponse) ProtoMessage()               {}
func (*UpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpResponse) GetInstances() []*UpMsgMeta {
	if m != nil {
		return m.Instances
	}
	return nil
}

type DownMsgMeta struct {
	ContainerId     string `protobuf:"bytes,1,opt,name=ContainerId,json=containerId" json:"ContainerId,omitempty"`
	ContainerStatus string `protobuf:"bytes,2,opt,name=ContainerStatus,json=containerStatus" json:"ContainerStatus,omitempty"`
	ImageStatus     string `protobuf:"bytes,3,opt,name=ImageStatus,json=imageStatus" json:"ImageStatus,omitempty"`
}

func (m *DownMsgMeta) Reset()                    { *m = DownMsgMeta{} }
func (m *DownMsgMeta) String() string            { return proto.CompactTextString(m) }
func (*DownMsgMeta) ProtoMessage()               {}
func (*DownMsgMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DownMsgMeta) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *DownMsgMeta) GetContainerStatus() string {
	if m != nil {
		return m.ContainerStatus
	}
	return ""
}

func (m *DownMsgMeta) GetImageStatus() string {
	if m != nil {
		return m.ImageStatus
	}
	return ""
}

type DownResponse struct {
	Instances []*DownMsgMeta `protobuf:"bytes,1,rep,name=Instances,json=instances" json:"Instances,omitempty"`
}

func (m *DownResponse) Reset()                    { *m = DownResponse{} }
func (m *DownResponse) String() string            { return proto.CompactTextString(m) }
func (*DownResponse) ProtoMessage()               {}
func (*DownResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DownResponse) GetInstances() []*DownMsgMeta {
	if m != nil {
		return m.Instances
	}
	return nil
}

type ListItem struct {
	FunctionID string `protobuf:"bytes,1,opt,name=FunctionID,json=functionID" json:"FunctionID,omitempty"`
	State      string `protobuf:"bytes,2,opt,name=State,json=state" json:"State,omitempty"`
	ServiceURL string `protobuf:"bytes,3,opt,name=ServiceURL,json=serviceURL" json:"ServiceURL,omitempty"`
}

func (m *ListItem) Reset()                    { *m = ListItem{} }
func (m *ListItem) String() string            { return proto.CompactTextString(m) }
func (*ListItem) ProtoMessage()               {}
func (*ListItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListItem) GetFunctionID() string {
	if m != nil {
		return m.FunctionID
	}
	return ""
}

func (m *ListItem) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ListItem) GetServiceURL() string {
	if m != nil {
		return m.ServiceURL
	}
	return ""
}

type ListResponse struct {
	Instances []*ListItem `protobuf:"bytes,1,rep,name=Instances,json=instances" json:"Instances,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListResponse) GetInstances() []*ListItem {
	if m != nil {
		return m.Instances
	}
	return nil
}

func init() {
	proto.RegisterType((*FunctionMeta)(nil), "api.FunctionMeta")
	proto.RegisterType((*UpRequest)(nil), "api.UpRequest")
	proto.RegisterType((*DownRequest)(nil), "api.DownRequest")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*UpMsgMeta)(nil), "api.UpMsgMeta")
	proto.RegisterType((*UpResponse)(nil), "api.UpResponse")
	proto.RegisterType((*DownMsgMeta)(nil), "api.DownMsgMeta")
	proto.RegisterType((*DownResponse)(nil), "api.DownResponse")
	proto.RegisterType((*ListItem)(nil), "api.ListItem")
	proto.RegisterType((*ListResponse)(nil), "api.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FxService service

type FxServiceClient interface {
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error)
	Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type fxServiceClient struct {
	cc *grpc.ClientConn
}

func NewFxServiceClient(cc *grpc.ClientConn) FxServiceClient {
	return &fxServiceClient{cc}
}

func (c *fxServiceClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error) {
	out := new(UpResponse)
	err := grpc.Invoke(ctx, "/api.FxService/Up", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error) {
	out := new(DownResponse)
	err := grpc.Invoke(ctx, "/api.FxService/Down", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/api.FxService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FxService service

type FxServiceServer interface {
	Up(context.Context, *UpRequest) (*UpResponse, error)
	Down(context.Context, *DownRequest) (*DownResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterFxServiceServer(s *grpc.Server, srv FxServiceServer) {
	s.RegisterService(&_FxService_serviceDesc, srv)
}

func _FxService_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/Up",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).Up(ctx, req.(*UpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/Down",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).Down(ctx, req.(*DownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FxService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FxService",
	HandlerType: (*FxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _FxService_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _FxService_Down_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FxService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fx.proto",
}

func init() { proto.RegisterFile("fx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x49, 0xdb, 0xdd, 0x6d, 0x4e, 0xd2, 0xd6, 0x8e, 0x5e, 0x84, 0x45, 0xa5, 0x0c, 0x22,
	0x65, 0x95, 0x06, 0xd7, 0x1b, 0xa9, 0x22, 0x8a, 0x65, 0x21, 0xd0, 0x85, 0x25, 0xa5, 0xf7, 0x8e,
	0xe9, 0x34, 0x3b, 0x90, 0xce, 0xc4, 0xcc, 0x64, 0x77, 0x41, 0xbc, 0xf1, 0x15, 0x7c, 0x2a, 0xaf,
	0x7d, 0x05, 0x1f, 0x44, 0x26, 0x99, 0x49, 0x53, 0x96, 0xbd, 0x9c, 0x3f, 0xe7, 0xfc, 0xe7, 0xfb,
	0xcf, 0x4c, 0xa0, 0xbf, 0xbd, 0x9b, 0xe5, 0x85, 0x50, 0x02, 0x75, 0x49, 0xce, 0x4e, 0x9f, 0xa6,
	0x42, 0xa4, 0x19, 0x0d, 0x49, 0xce, 0x42, 0xc2, 0xb9, 0x50, 0x44, 0x31, 0xc1, 0x65, 0x5d, 0x82,
	0xaf, 0xc0, 0xbf, 0x28, 0x79, 0xa2, 0xa5, 0x4b, 0xaa, 0x08, 0x42, 0xd0, 0x5b, 0x12, 0x9e, 0x06,
	0xce, 0xc4, 0x99, 0xba, 0x71, 0x2f, 0x23, 0x3c, 0xd5, 0xda, 0x15, 0x51, 0xd7, 0x41, 0xa7, 0xd6,
	0x72, 0xa2, 0xae, 0x51, 0x00, 0x27, 0x5f, 0x04, 0x57, 0x94, 0xab, 0xa0, 0x5b, 0xc9, 0x27, 0x49,
	0x7d, 0xc4, 0x1f, 0xc0, 0x5d, 0xe7, 0x31, 0xfd, 0x5e, 0x52, 0xa9, 0x50, 0x08, 0xae, 0xb5, 0x97,
	0x81, 0x33, 0xe9, 0x4e, 0xbd, 0xf3, 0xf1, 0x8c, 0xe4, 0x6c, 0xd6, 0x1e, 0x1a, 0xbb, 0x5b, 0x5b,
	0x83, 0x9f, 0x81, 0xb7, 0x10, 0xb7, 0xdc, 0xf6, 0x0f, 0xa1, 0x13, 0x2d, 0xaa, 0x46, 0x37, 0xee,
	0xb0, 0x85, 0xfe, 0xbc, 0x64, 0x52, 0x3d, 0xf4, 0xf9, 0xa7, 0x9e, 0x7d, 0x29, 0xd3, 0x2a, 0xca,
	0x4b, 0x18, 0xda, 0x29, 0x2b, 0x51, 0x16, 0x09, 0x35, 0xa1, 0x86, 0xdb, 0x03, 0x15, 0x61, 0xf0,
	0x97, 0x22, 0x21, 0xd9, 0xe7, 0xcd, 0xa6, 0xa0, 0x52, 0x9a, 0x98, 0x7e, 0xd6, 0xd2, 0xd0, 0x0b,
	0x18, 0xc4, 0x74, 0x27, 0x14, 0xb5, 0x45, 0x75, 0xe8, 0x41, 0xd1, 0x16, 0xf1, 0x1c, 0x40, 0x47,
	0x97, 0xb9, 0xe0, 0x92, 0xa2, 0xd7, 0xe0, 0x46, 0x5c, 0x2a, 0xc2, 0x13, 0x6a, 0xb3, 0x0f, 0xab,
	0xec, 0x0d, 0x62, 0xec, 0x32, 0x5b, 0x80, 0x7f, 0xd4, 0xc1, 0x2d, 0xfc, 0x04, 0x3c, 0xbd, 0x5f,
	0xc2, 0x38, 0x2d, 0xa2, 0x8d, 0x21, 0xf7, 0x92, 0xbd, 0x84, 0xa6, 0x30, 0x6a, 0x2a, 0x56, 0x8a,
	0xa8, 0xd2, 0x92, 0x8f, 0x92, 0x43, 0x59, 0x7b, 0x45, 0x3b, 0x92, 0x52, 0x53, 0x55, 0xa3, 0x7b,
	0x6c, 0x2f, 0xe1, 0x8f, 0xe0, 0xd7, 0x5b, 0x37, 0xe8, 0xb3, 0xfb, 0xe8, 0x8f, 0x2a, 0xf4, 0x16,
	0x62, 0x1b, 0xfe, 0x2b, 0xf4, 0xf5, 0xb5, 0x44, 0x8a, 0xee, 0xd0, 0x73, 0x00, 0xbb, 0xf6, 0xea,
	0x6e, 0xf4, 0x30, 0xd8, 0x36, 0x0a, 0x7a, 0x02, 0x47, 0x7a, 0x2a, 0x35, 0xb4, 0x47, 0x52, 0x1f,
	0x74, 0xd7, 0x8a, 0x16, 0x37, 0x2c, 0xa1, 0xeb, 0x78, 0x69, 0x10, 0x41, 0x36, 0x0a, 0x7e, 0x0f,
	0x7e, 0x7d, 0xf1, 0x86, 0xf0, 0xd5, 0x7d, 0xc2, 0x41, 0x45, 0x68, 0x39, 0x5a, 0x78, 0xe7, 0x7f,
	0x1c, 0x70, 0x2f, 0xee, 0x8c, 0x3f, 0x7a, 0x07, 0x9d, 0x75, 0x8e, 0xec, 0x55, 0x98, 0xa7, 0x74,
	0x3a, 0x6a, 0xce, 0xf5, 0x04, 0x3c, 0xfe, 0xf5, 0xf7, 0xdf, 0xef, 0x8e, 0x87, 0x8f, 0xc3, 0x9b,
	0x37, 0x61, 0x99, 0xcf, 0x9d, 0x33, 0xf4, 0x09, 0x7a, 0x7a, 0x01, 0x68, 0xbf, 0x0b, 0xdb, 0x3d,
	0x6e, 0x29, 0xa6, 0xff, 0x71, 0xd5, 0x3f, 0xc0, 0x7d, 0xdd, 0xbf, 0x11, 0xb7, 0xdc, 0x38, 0x68,
	0x40, 0xe3, 0xd0, 0x7a, 0xca, 0xc6, 0xa1, 0x9d, 0xf1, 0xd0, 0x21, 0x63, 0x52, 0xcd, 0x9d, 0xb3,
	0x6f, 0xc7, 0xd5, 0x7f, 0xfb, 0xf6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x43, 0xab, 0xb6,
	0xe6, 0x03, 0x00, 0x00,
}
