on: [push]
  # schedule:
  #   - cron: '0 12 * * *'
name: docker
jobs:
  Docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_version:
          - 18.09
          # - 19.03
          # - 19.09
        docker_channel:
          - stable
          # - test
    steps:
      - uses: actions/checkout@master
      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: ${{ matrix.docker_version }}
          docker_channel: ${{ matrix.docker_channel }}

      - name: login docker hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: build and publish fx d image
        if: always()
        run: |
          docker build -t metrue/fx-d-base:latest -f ./assets/dockerfiles/base/d/Dockerfile ./assets/dockerfiles/base/d
          docker push metrue/fx-d-base:latest

      - name: build and publish fx go image
        run: |
          docker build -t metrue/fx-go-base:latest -f ./assets/dockerfiles/base/go/Dockerfile ./assets/dockerfiles/base/go
          docker push metrue/fx-go-base:latest

      - name: build and publish fx node image
        if: always()
        run: |
          docker build -t metrue/fx-node-base:latest -f ./assets/dockerfiles/base/node/Dockerfile ./assets/dockerfiles/base/node
          docker push metrue/fx-node-base:latest

      - name: build and publish fx python image
        if: always()
        run: |
          docker build -t metrue/fx-python-base:latest -f ./assets/dockerfiles/base/python/Dockerfile ./assets/dockerfiles/base/python
      - name: publish fx python image
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker push metrue/fx-python-base:latest

      - name: build and publish fx perl image
        if: always()
        run: |
          docker build -t metrue/fx-perl-base:latest -f ./assets/dockerfiles/base/perl/Dockerfile ./assets/dockerfiles/base/perl
          docker push metrue/fx-perl-base:latest

      - name: build and publish fx julia image
        if: always()
        run: |
          docker build -t metrue/fx-julia-base:latest -f ./assets/dockerfiles/base/julia/Dockerfile ./assets/dockerfiles/base/julia
          docker push metrue/fx-julia-base:latest

      - name: build and publish fx crystal image
        if: always()
        run: |
          docker build -t metrue/fx-crystal-base:latest -f ./assets/dockerfiles/base/crystal/Dockerfile ./assets/dockerfiles/base/crystal
          docker push metrue/fx-crystal-base:latest

      - name: build and publish fx php image
        if: always()
        run: |
          docker build -t metrue/fx-php-base:latest -f ./assets/dockerfiles/base/php/Dockerfile ./assets/dockerfiles/base/php
          docker push metrue/fx-php-base:latest
